### ISSUE TITLE
Vox-inspired Page Management (epic)

### ISSUE THREAD

**Issue by gabrielhase** [upfrontIO/livingdocs-design-timeline#29]
We want to enable Page Management for our beta. For this we need to design list containers that can be used as `doc-includes` in the Beta.
For our Pages we want to take [http://www.vox.com](http://www.vox.com) as an inspiration, mainly using their structuring strategy (it's a really nice one). Of course we will adapt the teasers to our design with colors, fonts and maybe more (this is up to the designer).

The result should be a set of teaser containers and a Page layout to work with.

One thing we don't want to take from the Vox design is their mixing of odd and even element rows. We only want 4, 2 or 1 element per row (also in the responsive behavior). If you have three elements in a 4 element row, one spot will be blank.

**Comment by rawdiggie** [comment]
In the meantime, Vox has changed its design so it’s hard to check if everything has been done what was requested in this issue/epic. The only thing I can say for sure it that the placeholders don’t behave as expected. I’ve [created an issue](https://github.com/upfrontIO/livingdocs-design-timeline/issues/45) that I will try to take care of.

I will assume that Vedi implemented the requested page components and close this issue.
